### ISSUE TITLE
Game Crash When Opening Inventory With A Backpack Equipped

### ISSUE THREAD

**Issue by SweatoPants** [jptrzy/inventory-backpack-mod#15]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/15/22, 12:49 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void dev.emi.trinkets.TrinketPlayerScreenHandler.updateTrinketSlots(boolean)'
	at net.jptrzy.inventory.backpack.util.Utils.openBackpackHandler(Utils.java:150)
	at net.jptrzy.inventory.backpack.Main.lambda$registerPacketHandlers$1(Main.java:80)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756)
	at net.minecraft.class_1255.method_18857(class_1255.java:134)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:741)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by jptrzy** [comment]
This is weird, but I will look into it.
