### ISSUE TITLE
Unequipping backpacks in dedicated servers cause issues and will end up deleting the backpack.

### ISSUE THREAD

**Issue by BlindTwig** [jptrzy/inventory-backpack-mod#17]
This is specifically when the mod is on a dedicated server, does not happen otherwise. 

When unequipping, the inventory UI is not updated, allowing you to put the backpack inside itself. If you put it in your normal inventory, and reopen it, it will be normal, but when trying to move the backpack, it is deleted. If you move the backpack between the trinket slot and normal armor slot, it will lock your inventory, making you unable to open it. 

When unequipping the backpack from any slot, this is spit into the server log:
```[17:22:59] [Server thread/FATAL]: Error executing task on Server
java.lang.RuntimeException: Cannot load class net.jptrzy.inventory.backpack.client.Client in environment type SERVER
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?]
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:282) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:240) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.jptrzy.inventory.backpack.util.Utils.openBackpackHandler(Utils.java:141) ~[inventory-backpack-mod-0.2.4.jar:?]
	at net.jptrzy.inventory.backpack.Main.lambda$registerPacketHandlers$1(Main.java:75) ~[inventory-backpack-mod-0.2.4.jar:?]
	at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:780) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:162) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:762) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:756) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:134) ~[?:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:741) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:688) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Polarite** [comment]
Up↑
Happens on latest version of inventory backpacks
